export enum DocumentCategory {
  CMR = 'CMR',
  INVOICE = 'INVOICE',
  DELIVERY_NOTE = 'DELIVERY_NOTE',
  OCP_OCS = 'OCP_OCS',
  PAYMENT_CONFIRMATION = 'PAYMENT_CONFIRMATION',
  AGREEMENT = 'AGREEMENT',
  UNKNOWN = 'UNKNOWN',
  UNABLE_TO_CLASSIFY = 'UNABLE_TO_CLASSIFY'
}
